###############################################################################
# ANIMAÇÃO DO TRIÂNGULO DE SIERPINSKI — Jogo do Caos
# SIERPINSKI TRIANGLE ANIMATION — Chaos Game Method
# Usando / Using Luxor.jl
#
# Autor / Author:         Igo da Costa Andrade
# GitHub:                 https://github.com/costandrad
# TikTok:                 https://www.tiktok.com/@igoandrade
# Repositório / Repo:     https://github.com/costandrad/chaos-game-sierpinski-triangle
# Data / Date:            <2025-12-10>
#
# ---------------------------------------------------------------------------
# DESCRIÇÃO (PT-BR):
#   Este script cria uma animação vertical (formato TikTok — 1080×1920)
#   mostrando o processo iterativo conhecido como "Jogo do Caos" (Chaos Game),
#   que gera o famoso Triângulo de Sierpinski.
#
#   O código:
#     • Gera imagens quadro a quadro com Luxor.jl
#     • Mantém os pontos acumulados ao longo da animação
#     • Exporta automaticamente um GIF (e opcionalmente um MP4 via ffmpeg)
#     • Organiza toda a saída na pasta /output
#
# ---------------------------------------------------------------------------
# DESCRIPTION (EN):
#   This script creates a vertical animation (TikTok format — 1080×1920)
#   showing the iterative process known as the "Chaos Game", which constructs
#   the well-known Sierpinski Triangle.
#
#   The code:
#     • Generates frame-by-frame images using Luxor.jl
#     • Keeps all generated points accumulated throughout the animation
#     • Automatically exports a GIF (and optionally an MP4 using ffmpeg)
#     • Organizes all output under the /output directory
#
# Licença / License:      <MIT>
###############################################################################

using Luxor, Random, Printf

# ---------------------------------------------------------------------------
# Função auxiliar: recria um diretório (remove se existir e cria novo)
# Utility function: recreate a directory (remove if exists, then create)
# ---------------------------------------------------------------------------
function create_dir(complete_dir_name)
    if isdir(complete_dir_name)
        rm(complete_dir_name; force=true, recursive=true)
    end
    mkdir(complete_dir_name)
end


begin
    ###############################################################################
    # CONFIGURAÇÕES GERAIS DA ANIMAÇÃO / GENERAL ANIMATION SETTINGS
    ###############################################################################
    total_frames = 2000          # Número total de quadros / Total number of frames
    frame_rate   = 120           # FPS do vídeo / Frames per second of output

    width  = 1080                # Largura — formato vertical / Width — vertical format
    height = 1920                # Altura — formato 9:16 / Height — 9:16 aspect ratio


    ###############################################################################
    # PARÂMETROS DO TRIÂNGULO DE SIERPINSKI / SIERPINSKI TRIANGLE PARAMETERS
    ###############################################################################
    n    = 3                     # Número de vértices (triângulo) / Number of vertices (triangle)
    α    = 2π / n                # Ângulo entre vértices / Angle between vertices
    raio = 0.5 * width           # Raio do círculo circunscrito ao triângulo (R) / Radius of the circumscribed triangle's circle (R)

    # Armazena todos os pontos gerados pelo Jogo do Caos / Stores all points generated by Chaos Game
    positions = [Point(0, 0)]


    ###############################################################################
    # ESTRUTURA DE PASTAS (OUTPUT / FRAMES) / FOLDER STRUCTURE (OUTPUT / FRAMES)
    ###############################################################################
    project_dir = pwd()
    main_name   = @sprintf("sierpinski_anim_f%d_fps%d", total_frames, frame_rate)

    output_dir = joinpath(project_dir, "output", main_name)
    frames_dir = joinpath(output_dir, "frames")

    create_dir(output_dir)
    create_dir(frames_dir)


    ###############################################################################
    # CRIAÇÃO DO OBJETO MOVIE / CREATION OF MOVIE OBJECT
    ###############################################################################
    movie_sierpinski = Movie(width, height, main_name, 1:total_frames)


    ###############################################################################
    # FUNÇÃO DE CENÁRIO (FUNDO / TEXTOS) / BACKDROP FUNCTION (BACKGROUND / TEXT)
    ###############################################################################
    function backdrop(scene, frame)
        background("black")

        # Título principal / Main title
        setfont("Arial Bold", 80)
        setcolor("white")
        settext("Jogo do Caos",
            Point(0, -0.35 * height),
            halign = "center", valign = "center")

        # Subtítulo / Subtitle
        setfont("Arial", 72)
        settext("Triângulo de Sierpinski",
            Point(0, 0.20 * height),
            halign = "center", valign = "center")

        # Número do frame / Frame number
        setfont("Arial", 60)
        settext(@sprintf("n = %4d", frame),
            Point(0, 0.25 * height),
            halign = "center", valign = "center")
    end


    ###############################################################################
    # FUNÇÃO DO MÉTODO DO JOGO DO CAOS (SIERPINSKI) / CHAOS GAME METHOD FUNCTION
    ###############################################################################
    function sierpinski(scene, frame)
        # Cálculo dos vértices do triângulo / Compute the triangle vertices
        vertices = [
            Point(
                raio * cos((k - 1) * α - π/2),
                raio * sin((k - 1) * α - π/2)
            )
            for k in 1:n
        ]

        # Desenha o triângulo base / Draw the base triangle
        setline(3)
        setcolor("white")
        ngon(Point(0, 0), raio, n, -π/2, action = :stroke)

        # Parâmetros visuais das partículas / Visual parameters for points
        setcolor("blue")

        # Passo do Jogo do Caos / Chaos Game step
        vertice = vertices[rand(1:n)]
        p = midpoint(positions[end], vertice)

        # Guarda o ponto acumulado / Save the accumulated point
        push!(positions, p)

        # Desenha a trilha acumulada / Draw all accumulated points
        for point in positions
            circle(point, 3, :fill)
        end

        # Destaque do ponto atual / Highlight the current point
        setcolor("white")
        circle(p, 15, :fill)
    end


    ###############################################################################
    # EXECUÇÃO DA ANIMAÇÃO / ANIMATION EXECUTION
    ###############################################################################
    animate(
        movie_sierpinski,
        [
            Scene(movie_sierpinski, backdrop,   1:total_frames),
            Scene(movie_sierpinski, sierpinski, 1:total_frames)
        ],
        creategif     = true,
        framerate     = frame_rate,
        tempdirectory = frames_dir,
        pathname      = joinpath(output_dir, "$(main_name).gif")
    )

    ###############################################################################
    # EXPORTAÇÃO OPCIONAL PARA MP4 (requer ffmpeg instalado)
    # OPTIONAL MP4 EXPORT (requires ffmpeg installed)
    ###############################################################################

    # Caminho completo do arquivo de saída / Output MP4 file path
    mp4_path = joinpath(output_dir, "$(main_name).mp4")

    # Comando ffmpeg
    cmd = `ffmpeg -r $frame_rate -i "$frames_dir/%10d.png" -c:v h264 -crf 0 "$mp4_path"`

    println("\nGerando MP4 com ffmpeg...\nGenerating MP4 with ffmpeg...\n")
    println(cmd)

    # Executa o comando / Execute the command
    run(cmd)

    println("\nMP4 gerado em: $mp4_path\nMP4 generated at: $mp4_path")

end
